#!/bin/bash

if [ -n "$1" ]; then
    echo "Select an application: $1" 
    app=$1
else
    echo "Select an application:"
    cf a 
    read -p 'Name: ' app
fi

guid=$(cf curl '/v3/apps' | jq -c ".resources[] |  select(.name==\"$app\") | .guid" | sed 's/"//g')

echo "/v3/apps/$guid/env"

cf curl "/v3/apps/$guid/env" | jq '.system_env_json' > default-env.json 