image: santiagogm1995/sapui5gitlab:1.0.0
stages:
  - prepare
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - mta_archives/
prepare_env:
  stage: prepare
  script:
    - npm i
test_pupeeter:
  stage: test
  script:
    - npx npm test
test_lint:
  stage: test
  script:
    - npx eslint uimodule/
deploy_cf:
  stage: deploy
  script:
    - sed -i "s/TestSapui5/$CI_PROJECT_NAME-$CI_COMMIT_BRANCH/gi" mta.yaml
    - sed -i "s/TestSapui5/$CI_PROJECT_NAME-$CI_COMMIT_BRANCH/gi" package.json
    - cf login -a $CF_ENDPOINT -u $USERNAME -p $PASSWORD -o $CF_ORG -s $CF_SPACE
    - echo $CI_COMMIT_BRANCH
    - echo $CI_PROJECT_NAME
    - npm run deploy
  environment:
    name: Cloud foundry
    url: https://cockpit.hanatrial.ondemand.com/trial
